version: '3'
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    restart: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 9000:9000
      - 8123:8123
    volumes:
      - clickhouse:/var/lib/clickhouse
volumes:
  redis:
  postgres:
  clickhouse: